redapp_operations:
    resource: "@RedappOperationsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

operations:
    type:     rest
    resource: AppBundle\Controller\OperationController

users:
    type:     rest
    resource: AppBundle\Controller\UserController

categories:
    type:     rest
    resource: AppBundle\Controller\CategoryController