AppBundle\Entity\Operation:
    attributes:
        id:
            groups: ['operation', 'user']
        name:
            groups: ['operation', 'user']
        type:
            groups: ['operation', 'user']
        price:
            groups: ['operation', 'user']
        description:
            groups: ['operation', 'user']
        operation_date:
            groups: ['operation', 'user']
        created:
            groups: ['operation', 'user']      
        user:
            groups: ['operation']

AppBundle\Entity\User:
    attributes:
        id:
            groups: ['operation', 'user', 'auth-token']
        fullname:
            groups: ['operation', 'user', 'auth-token']
        email:
            groups: ['operation', 'user', 'auth-token']

AppBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']
