AppBundle\Entity\Operation:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        type:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        fullname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~

AppBundle\Entity\Category:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        parent:
            - NotBlank: ~
            - Type: integer